-- MySQL Script generated by MySQL Workbench
-- Sun Jun  5 12:18:02 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema merca_facil
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema merca_facil
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `merca_facil` DEFAULT CHARACTER SET utf8 ;
USE `merca_facil` ;

-- -----------------------------------------------------
-- Table `merca_facil`.`PROVEEDORES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merca_facil`.`PROVEEDORES` (
  `NIT` INT NOT NULL,
  `Nombre` VARCHAR(255) NOT NULL,
  `Dirección` VARCHAR(255) NOT NULL,
  `Teléfono` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`NIT`));


-- -----------------------------------------------------
-- Table `merca_facil`.`ARTICULOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merca_facil`.`ARTICULOS` (
  `Código` INT NOT NULL,
  `Nombre` VARCHAR(255) NOT NULL,
  `Unidad de Medida` VARCHAR(20) NOT NULL,
  `Existencia` INT NOT NULL,
  `Cant_Max` INT NOT NULL,
  `Cant_Min` INT NOT NULL,
  `Proveedor` INT NOT NULL,
  PRIMARY KEY (`Código`),
  INDEX `Proveedor_idx` (`Proveedor` ASC) VISIBLE,
  CONSTRAINT `Proveedor`
    FOREIGN KEY (`Proveedor`)
    REFERENCES `merca_facil`.`PROVEEDORES` (`NIT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `merca_facil`.`CLIENTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merca_facil`.`CLIENTES` (
  `Cédula` INT NOT NULL,
  `Nombre` VARCHAR(80) NOT NULL,
  `Dirección` VARCHAR(80) NOT NULL,
  `Teléfono` VARCHAR(55) NOT NULL,
  PRIMARY KEY (`Cédula`));


-- -----------------------------------------------------
-- Table `merca_facil`.`TIENDAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merca_facil`.`TIENDAS` (
  `Código_Almacen` INT NOT NULL,
  `Nombre` VARCHAR(255) NOT NULL,
  `Dirección` VARCHAR(80) NULL,
  `Nombre_Gerente` VARCHAR(80) NOT NULL,
  `TIENDAScol` VARCHAR(45) NULL,
  PRIMARY KEY (`Código_Almacen`));


-- -----------------------------------------------------
-- Table `merca_facil`.`COMPRA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merca_facil`.`COMPRA` (
  `Nro_Factura` INT NOT NULL,
  `Articulo` INT NOT NULL,
  `Proveedor` INT NOT NULL,
  `Tienda` INT NOT NULL,
  `Fecha` DATETIME NOT NULL,
  `Valor_Total_Compra` INT NOT NULL,
  `Cant_Articulos` INT NOT NULL,
  `Tipo_Compra` VARCHAR(45) NOT NULL,
  `Valor_Articulo` INT NOT NULL,
  PRIMARY KEY (`Nro_Factura`),
  INDEX `Articulo_idx` (`Articulo` ASC) VISIBLE,
  INDEX `Proveedor_idx` (`Proveedor` ASC) VISIBLE,
  INDEX `Tienda_idx` (`Tienda` ASC) VISIBLE,
  CONSTRAINT `Articulo`
    FOREIGN KEY (`Articulo`)
    REFERENCES `merca_facil`.`ARTICULOS` (`Código`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `NIT`
    FOREIGN KEY (`Proveedor`)
    REFERENCES `merca_facil`.`PROVEEDORES` (`NIT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Tienda`
    FOREIGN KEY (`Tienda`)
    REFERENCES `merca_facil`.`TIENDAS` (`Código_Almacen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `merca_facil`.`VENTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merca_facil`.`VENTA` (
  `Nro_Factura` INT NOT NULL,
  `Articulo` INT NOT NULL,
  `Cliente` INT NOT NULL,
  `Tienda` INT NOT NULL,
  `Fecha` DATETIME NOT NULL,
  `Valor_Total_Venta` INT NOT NULL,
  `Cant_Articulos` INT NOT NULL,
  `Tipo_Venta` VARCHAR(45) NOT NULL,
  `Valor_Articulo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Nro_Factura`),
  INDEX `Articulo_idx` (`Articulo` ASC) VISIBLE,
  INDEX `Cliente_idx` (`Cliente` ASC) VISIBLE,
  INDEX `Tienda_idx` (`Tienda` ASC) VISIBLE,
  CONSTRAINT `Arti`
    FOREIGN KEY (`Articulo`)
    REFERENCES `merca_facil`.`ARTICULOS` (`Código`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Cliente`
    FOREIGN KEY (`Cliente`)
    REFERENCES `merca_facil`.`CLIENTES` (`Cédula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Tiendas`
    FOREIGN KEY (`Tienda`)
    REFERENCES `merca_facil`.`TIENDAS` (`Código_Almacen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
